---
- name: Install SQuirreL SQL Client for all users (silent mode)
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required dependencies
      apt:
        name:
          - curl
          - desktop-file-utils
          - rsync
          - openjdk-17-jre
        state: present

    - name: Create temp and opt directories
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /tmp
        - /opt/squirrel-sql-5.0.0

    - name: Download SQuirreL SQL installer JAR
      get_url:
        url: "https://sourceforge.net/projects/squirrel-sql/files/5.0.0/squirrel-sql-5.0.0-standard.jar/download"
        dest: "/tmp/squirrel-sql-5.0.0-standard.jar"
        mode: "0644"
      register: download_result
      retries: 3
      delay: 10
      until: download_result is succeeded
      ignore_errors: yes

    - name: Copy local JAR if download failed
      copy:
        src: ./squirrel-sql-5.0.0-standard.jar
        dest: /tmp/squirrel-sql-5.0.0-standard.jar
      when: download_result is failed

    - name: Copy auto-install.xml to /tmp
      copy:
        src: ./auto-install.xml
        dest: /tmp/auto-install.xml
        mode: "0644"

    - name: Run SQuirreL SQL installer in silent mode
      command: >
        java -jar /tmp/squirrel-sql-5.0.0-standard.jar
        -options /tmp/auto-install.xml
      args:
        chdir: /opt
      environment:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    - name: Make installation directory executable
      file:
        path: /usr/local/squirrel-sql-5.0.0
        mode: "0755"
        recurse: yes

    - name: Create symlink for global access
      file:
        src: /usr/local/squirrel-sql-5.0.0/squirrel-sql.sh
        dest: /usr/local/bin/squirrelsql
        state: link
        force: yes

    - name: Create desktop entry for all users
      copy:
        dest: /usr/share/applications/squirrelsql.desktop
        content: |
          [Desktop Entry]
          Name=SQuirreL SQL Client
          Exec=/usr/local/bin/squirrelsql
          Icon=/usr/local/squirrel-sql-5.0.0/icons/acorn.png
          Type=Application
          Categories=Development;Database;
          Terminal=false

    - name: Update desktop database
      command: update-desktop-database /usr/share/applications/

    - name: Validate desktop file
      command: desktop-file-validate /usr/share/applications/squirrelsql.desktop
