---
- name: Install and configure Nix with packages for all users (Ubuntu)
  hosts: all
  become: true

  vars:
    nix_packages:
      - awscli2
      - vscode
      - datagrip
      - drawio
      - duplicity
      - go
      - intellij-idea-community
      - intellij-idea-ultimate
      - mysql-workbench
      - postman
      - sqlitebrowser
      - eclipse
      - sublime4
      - yq
      - k9s
      - kubectl
      - helm
      - terraform
      - kubectx

  tasks:
    - name: Ensure curl and sudo are installed
      apt:
        name:
          - curl
          - sudo
        state: present
        update_cache: yes

    - name: Install Nix (multi-user mode)
      ansible.builtin.shell: |
        if [ ! -d /nix ]; then
          sh <(curl -L https://nixos.org/nix/install) --daemon
        fi
      args:
        creates: /nix

    - name: Allow unfree packages in Nix
      ansible.builtin.copy:
        dest: /etc/nix/nix.conf
        content: |
          experimental-features = nix-command flakes
          allow-unfree = true
        owner: root
        group: root
        mode: '0644'

    - name: Ensure Nix daemon service is enabled and running
      ansible.builtin.systemd:
        name: nix-daemon
        state: started
        enabled: true

    - name: Ensure Nix profile is available to all users
      ansible.builtin.copy:
        dest: /etc/profile.d/nix.sh
        content: |
          if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
            . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
          fi
        owner: root
        group: root
        mode: '0644'

    - name: Install Nix packages (system-wide)
      ansible.builtin.shell: |
        source /etc/profile.d/nix.sh
        nix-env -iA nixpkgs.{{ item }}
      loop: "{{ nix_packages }}"
      environment:
        NIX_PATH: nixpkgs=https://nixos.org/channels/nixpkgs-unstable
      args:
        executable: /bin/bash

    - name: Verify installed Nix packages
      ansible.builtin.shell: |
        source /etc/profile.d/nix.sh
        nix-env -q
      register: nix_installed
      changed_when: false

    - name: Show installed packages
      debug:
        msg: "{{ nix_installed.stdout_lines }}"
